### ISSUE TITLE
Not working with old tvh 4.0.8

### ISSUE THREAD

**Issue by bismosa** [arneman/tvh_upd_autorec#1]
Hello,

many thanks for the script and idea to workaround the issue.

I have an older tvh (4.0.8) running on a raspberry pi with openelec running.
I only have python 2.7.3 running on it.

I have tested the script. The imports are not working with a sub-directory. So i have changed them.
I get the error:
```
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    msg = HTSP.hello()
  File "/var/media/HDD1/Video/bugfix/htsp.py", line 78, in hello
    resp = self.recv()
  File "/var/media/HDD1/Video/bugfix/htsp.py", line 66, in recv
    ret = htsmsg.deserialize(self._sock, False)
  File "/var/media/HDD1/Video/bugfix/htsmsg.py", line 261, in deserialize
    ret = ret.next()
  File "/var/media/HDD1/Video/bugfix/htsmsg.py", line 257, in next
    return deserialize0(data)
  File "/var/media/HDD1/Video/bugfix/htsmsg.py", line 167, in deserialize0
    dlen = bin2int(data[2:6])
  File "/var/media/HDD1/Video/bugfix/htsmsg.py", line 32, in bin2int
    return struct.unpack(">i", d)[0]
struct.error: unpack requires a string argument of length 4
```

Than i have tested with an older Version of the files: 
```
wget https://raw.githubusercontent.com/tvheadend/tvheadend/release/4.0/lib/py/tvh/htsp.py
wget https://raw.githubusercontent.com/tvheadend/tvheadend/release/4.0/lib/py/tvh/htsmsg.py
wget https://raw.githubusercontent.com/tvheadend/tvheadend/release/4.0/lib/py/tvh/log.py
```
I had to move it under the same folder as the script. In the script i have changed:
`from htsp import HTSPClient`
But i get only 
```
Authentification successful
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    upd_all()
  File "main.py", line 32, in upd_all
    autorecs = get_autorecs()
  File "main.py", line 18, in get_autorecs
    HTSP.send('api', {'path': 'dvr/autorec/grid', 'args': {}})
  File "/var/media/HDD1/Video/bugfix/htsp.py", line 61, in send
    self._sock.send(htsmsg.serialize(args))
  File "/var/media/HDD1/Video/bugfix/htsmsg.py", line 128, in serialize
    cnt  = binary_count(msg)
  File "/var/media/HDD1/Video/bugfix/htsmsg.py", line 96, in binary_count
    ret = ret + _binary_count(f)
  File "/var/media/HDD1/Video/bugfix/htsmsg.py", line 84, in _binary_count
    raise Exception('invalid data type')
Exception: invalid data type
```

See you a chance to get it working?

Reagrds
Bismosa

**Comment by bismosa** [comment]
Hello,

i have tried the whole day...and now i have found a way to modify the recordings:

```
# -*- coding: utf-8 -*-
"""
Update all autorec entries to delete wrong schedules 

Should be started after each restart of tvheadend.

  see https://tvheadend.org/issues/5056
  see https://tvheadend.org/issues/4454

Idea from Arne Drees / Script from Bismosa
"""

#SETUP
TVHURL="http://localhost:9981" #e.g. "http://localhost:9981"

import json
import urllib2

if __name__ == '__main__':
    url = TVHURL + "/api/dvr/autorec/grid?limit=9999"
    response = urllib2.urlopen(url)
    json_object = json.load(response)
    
    for item in json_object["entries"]:
		if (item["start_window"] != "Any"):
			print item["start_window"]
			print item["uuid"]
			print item["content_type"]
			print item["start"]
			print item["start_window"]
			
			comment="bugfix"
			try:
				print item["comment"]
				if (item["comment"] == "bugfix"):
					comment="...bugfix..."
				else:
					comment="bugfix"
			except:
				print "no comment found"
			#UPDATE
			#http://openelec:9981/api/idnode/save?node={%22uuid%22:%2297dc6e99ef257be714330b7b1c26e979%22}
			#,"start": "18:00","start_window": "23:00"
			url = TVHURL + "/api/idnode/save?node={%22uuid%22:%22"+str(item['uuid'])+"%22,%22content_type%22:%22"+str(item['content_type'])+"%22"
			url += ",%22start%22:%22"+str(item['start'])+"%22,%22start_window%22:%22"+str(item['start_window'])+"%22,%22comment%22:%22"+str(comment)+"%22}"
			print url
			response = urllib2.urlopen(url)
			print response.read()
			if (response.read()) == "":
				print "success"
			else:
				print "failed"
```

I did not get it to work with the htsp lib. So i use only urls.
If no user/password ist set you must only enter the hostname.

Without changing anything the recordings will not be updating. So i use the comment field and change the comment every time the script runs (only changing the recordings where "start_window" is set)

It seems to be working great.

Many thanks for the idea! 
If you wish you can use the code as an alternative method. 
I would be glad if you write an indication in the readme.

Regards 
Bismosa
